/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibrarySlugTsRouteImport } from './routes/library.$slug.$ts'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LibraryRoute,
} as any)
const LibrarySlugTsRoute = LibrarySlugTsRouteImport.update({
  id: '/$slug/$ts',
  path: '/$slug/$ts',
  getParentRoute: () => LibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/studio': typeof StudioRoute
  '/library/': typeof LibraryIndexRoute
  '/library/$slug/$ts': typeof LibrarySlugTsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/studio': typeof StudioRoute
  '/library': typeof LibraryIndexRoute
  '/library/$slug/$ts': typeof LibrarySlugTsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/review': typeof ReviewRoute
  '/setup': typeof SetupRoute
  '/studio': typeof StudioRoute
  '/library/': typeof LibraryIndexRoute
  '/library/$slug/$ts': typeof LibrarySlugTsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/library'
    | '/login'
    | '/review'
    | '/setup'
    | '/studio'
    | '/library/'
    | '/library/$slug/$ts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/review'
    | '/setup'
    | '/studio'
    | '/library'
    | '/library/$slug/$ts'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/login'
    | '/review'
    | '/setup'
    | '/studio'
    | '/library/'
    | '/library/$slug/$ts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReviewRoute: typeof ReviewRoute
  SetupRoute: typeof SetupRoute
  StudioRoute: typeof StudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/library/$slug/$ts': {
      id: '/library/$slug/$ts'
      path: '/$slug/$ts'
      fullPath: '/library/$slug/$ts'
      preLoaderRoute: typeof LibrarySlugTsRouteImport
      parentRoute: typeof LibraryRoute
    }
  }
}

interface LibraryRouteChildren {
  LibraryIndexRoute: typeof LibraryIndexRoute
  LibrarySlugTsRoute: typeof LibrarySlugTsRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryIndexRoute: LibraryIndexRoute,
  LibrarySlugTsRoute: LibrarySlugTsRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  ReviewRoute: ReviewRoute,
  SetupRoute: SetupRoute,
  StudioRoute: StudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
